# Dependabot: weekly dependency updates for Go modules, GitHub Actions and Docker base images.
# Review PRs manually — no auto-merge (health-adjacent backend).
# See LICENSE_POLICY.md; CI runs ./scripts/check_licenses.sh on every PR.

version: 2

updates:
  - package-ecosystem: gomod
    directory: /
    schedule:
      interval: weekly
      day: monday
      time: "09:00"
      timezone: America/Sao_Paulo
    open-pull-requests-limit: 5
    labels:
      - dependencies
      - go
    commit-message:
      prefix: chore
      include: scope
    groups:
      go-minor-patch:
        patterns:
          - "*"
        update-types:
          - minor
          - patch

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
      day: monday
      time: "09:00"
      timezone: America/Sao_Paulo
    open-pull-requests-limit: 3
    labels:
      - dependencies
      - ci
    commit-message:
      prefix: chore
      include: scope
    groups:
      github-actions:
        patterns:
          - "*"

  - package-ecosystem: docker
    directory: /
    schedule:
      interval: weekly
      day: monday
      time: "09:00"
      timezone: America/Sao_Paulo
    open-pull-requests-limit: 2
    labels:
      - dependencies
      - docker
    commit-message:
      prefix: chore
      include: scope
